### ISSUE TITLE
Checked ✓

### ISSUE THREAD

**Issue by iamapurba2003** [himangshuishere/Web-Dev#4]
**I just Saw your Code**, pretty informative ... Go on ... But one file is empty **_JsVariables_** ... Why? 
# This Comment is to notify that I have checked your code 

- [x] Code Checked
- [x] All Ok

Close the issue once you receive this comment & check it out ... 
@himangshuishere

**Comment by himangshuishere** [comment]
@iamapurba2003 JS-Variables.js is not empty now... Some files are updated and new ones are added... Please check and ignore this comment after reading.
